# Generated by Django 6.0 on 2026-02-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/', verbose_name='Archivo de Diseño (PDF/AI/PNG)'),
        ),
    ]
