# Generated by Django 6.0 on 2026-02-07 22:16

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_finalproduct_design_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproduct',
            name='sale_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='sale_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PEN', 'Peruvian Sol'), ('USD', 'US Dollar')], default='PEN', editable=False, max_length=3),
        ),
    ]
