# Generated by Django 6.0 on 2026-02-07 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_finalproduct_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='finalproduct',
            options={},
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/', verbose_name='Archivo de Diseño Principal'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='designs/extras/', verbose_name='Archivo Adicional')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='production.finalproduct')),
            ],
        ),
    ]
