# Generated by Django 6.0 on 2026-02-07 22:34

import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_baseproduct_cost_and_more'),
        ('production', '0004_alter_billofmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='other_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'PEN'), max_digits=14, verbose_name='Otros Costos (Mano de obra, etc)'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='other_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PEN', 'Peruvian Sol'), ('USD', 'US Dollar')], default='PEN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='supplies_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'PEN'), max_digits=14, verbose_name='Costo Insumos (Manual)'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='supplies_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PEN', 'Peruvian Sol'), ('USD', 'US Dollar')], default='PEN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='supplies',
            field=models.ManyToManyField(blank=True, through='production.BillOfMaterial', to='inventory.supply', verbose_name='Insumos Requeridos'),
        ),
    ]
