# Generated by Django 6.0 on 2026-02-07 21:53

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_supply_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base_products/', verbose_name='Imagen del Producto Base (Mockup)'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
