# Generated by Django 6.0 on 2026-02-07 22:16

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_baseproduct_category_baseproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PEN', 'Peruvian Sol'), ('USD', 'US Dollar')], default='PEN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='supply',
            name='cost_per_unit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Costo por Unidad'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='cost_per_unit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PEN', 'Peruvian Sol'), ('USD', 'US Dollar')], default='PEN', editable=False, max_length=3),
        ),
    ]
