# Generated by Django 6.0 on 2026-02-07 22:16

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'PEN'), max_digits=14, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PEN', 'Peruvian Sol'), ('USD', 'US Dollar')], default='PEN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PEN', 'Peruvian Sol'), ('USD', 'US Dollar')], default='PEN', editable=False, max_length=3),
        ),
    ]
